#!/bin/sh
#
# Wraps the chair firmware image in a C header for the ESP32 bridge to carry.
#
#   gen-image-header.sh build/socozi.bin 0x1234abcd > socozi_image.h
#
# The array is const, so on ESP32 it lives in flash and is memory-mapped rather
# than copied into RAM. 60 KiB against the XIAO's 4 MiB is not a constraint.
#
# `xxd -i` would do this in one line, but it is a vim extra and not on every
# machine. od is POSIX.
set -eu

bin=$1
version=$2

size=$(wc -c < "$bin" | tr -d ' ')

cat <<EOF
/* Generated by tools/gen-image-header.sh. Do not edit. */
#pragma once

#include <stdint.h>

/* $bin, $size bytes. */
#define SOCOZI_IMAGE_VERSION $version
#define SOCOZI_IMAGE_SIZE    ${size}u

/* Flashed to 0x08000000. Must stay clear of the settings store at 0x0800F000;
 * the linker script keeps the image to 60 KiB, and the bridge bounds-checks it
 * again before erasing anything.
 */
/* inline, not static: ESPHome pulls every component header into esphome.h,
 * and a static array there would be duplicated in each translation unit
 * that sees it. */
inline constexpr uint8_t SOCOZI_IMAGE[] = {
EOF

od -An -v -tu1 "$bin" |
  awk '{
    for (i = 1; i <= NF; i++) {
      printf "%s0x%02x,", (n % 12 == 0 ? "    " : " "), $i
      if (++n % 12 == 0) printf "\n"
    }
  }
  END { if (n % 12) printf "\n" }'

echo "};"
