/* Emits the debug block's layout as a C header, for the ESP32 bridge.
 *
 * Built by the *host* compiler with the same -D flags as the firmware, so the
 * offsets it prints are the ones the firmware being built actually uses. The
 * struct is #if-guarded on the enhancement flags, which makes its layout a
 * property of a particular build rather than of the source tree — so the bridge
 * gets told, rather than assuming. See docs/esphome-design.md §2.
 *
 * Offsets are in words. Every field in the block is a uint32_t, which is also
 * what makes the completeness check below exact: if the field list here has
 * fallen behind debug.h, the count will not match sizeof and the build stops.
 * A silently missing field would otherwise cost an entity in Home Assistant and
 * nothing would ever say so.
 */

#include <stdio.h>
#include <stddef.h>

#include "debug.h"
#include "adjust.h"
#include "heat.h"
#include "motion.h"
#include "pneumatics.h"
#include "version.h"

#define BASE_FIELDS \
    F(magic) F(ticks) \
    F(adc) F(adc_min) F(adc_max) F(adc_ch7_max) F(adc_ch8) F(adc_ch9) \
    F(adc_flags) \
    F(istat_a) F(istat_b) F(istat_c) F(octl_a) F(octl_b) F(octl_c) \
    F(inputs) F(inputs_seen) \
    F(hs_frames) F(hs_polls) F(hs_bytes) F(hs_last_byte) F(hs_errors) \
    F(hs_last_error) F(hs_button) F(leds) F(presses) \
    F(motion) F(motion_ms) F(stops) F(stalls) \
    F(power_on) F(valves) F(massage_on) F(massage_step) F(massage_ms) \
    F(lumbar_state) \
    F(heat_on) F(heat_ms)

#if ENH_END_OF_TRAVEL_STOP
#define F_ARRIVALS F(arrivals)
#else
#define F_ARRIVALS
#endif

#if ENH_POWER_DOUBLE_TAP
#define F_AUTO_MOVES F(auto_moves)
#else
#define F_AUTO_MOVES
#endif

#if ENH_HEAT_LEVELS
#define F_HEAT_LEVEL F(heat_level)
#else
#define F_HEAT_LEVEL
#endif

#if ENH_SETTINGS_PERSIST
#define F_SETTINGS F(settings_writes) F(settings_erases) F(settings_errors)
#else
#define F_SETTINGS
#endif

#if ENH_LUMBAR_HOLD_SET
#define F_LUMBAR_LEVEL F(lumbar_level)
#else
#define F_LUMBAR_LEVEL
#endif

#if ENH_MASSAGE_LEVELS
#define F_MASSAGE_LEVEL F(massage_level)
#else
#define F_MASSAGE_LEVEL
#endif

#if ENH_POSITION_TRACK
#define F_POSITION F(pos_recline) F(pos_headrest)
#else
#define F_POSITION
#endif

#if ENH_PRESET
#define F_PRESET F(presets_saved) F(presets_recalled)
#else
#define F_PRESET
#endif

#if BRIDGE
#define F_BRIDGE F(version) F(rtt_cb)
#else
#define F_BRIDGE
#endif

#define FIELDS \
    BASE_FIELDS \
    F_ARRIVALS F_AUTO_MOVES F_HEAT_LEVEL F_SETTINGS F_LUMBAR_LEVEL \
    F_MASSAGE_LEVEL F_POSITION F_PRESET F_BRIDGE

int main(void)
{
    size_t words = sizeof(struct debug_block) / 4;
    size_t listed = 0;

#define F(name) listed++;
    FIELDS
#undef F

    if (listed != words) {
        fprintf(stderr,
                "gen-dbg-layout: field list has %zu entries, "
                "struct debug_block is %zu words. Update FIELDS in %s.\n",
                listed, words, __FILE__);
        return 1;
    }

    printf("/* Generated by tools/gen-dbg-layout.c. Do not edit. */\n");
    printf("#pragma once\n\n");

    /* Pinned there by gd32e230c8.ld, which is what makes reading it a single
     * SWD block transfer with no symbol lookup.
     */
    printf("#define SOCOZI_DBG_BASE   0x20000000u\n");
    printf("#define SOCOZI_DBG_MAGIC  0x%08xu\n", DEBUG_MAGIC);
    printf("#define SOCOZI_DBG_WORDS  %zu\n\n", words);

#define F(name) \
    printf("#define SOCOZI_OFF_%-16s %zu\n", #name, \
           offsetof(struct debug_block, name) / 4);
    FIELDS
#undef F

    printf("\n/* Scaling and decoding constants, from the same build. */\n");
    printf("#define SOCOZI_FW_VERSION 0x%08xu\n", (unsigned)FW_VERSION);
    printf("#define SOCOZI_LEVEL_MAX  %u\n", (unsigned)ADJUST_LEVEL_MAX);
    printf("#define SOCOZI_HEAT_MAX_MS %uu\n", (unsigned)HEAT_TIMEOUT_MS);
    printf("#define SOCOZI_MASSAGE_MAX_MS %uu\n", (unsigned)MASSAGE_TIMEOUT_MS);
    printf("#define SOCOZI_LUMBAR_MAX_MS %uu\n", (unsigned)LUMBAR_INFLATE_MAX_MS);
    printf("#define SOCOZI_LUMBAR_UNIT_MS %uu\n", (unsigned)MASSAGE_TICK_MS);

#if ENH_POSITION_TRACK
    printf("#define SOCOZI_TRAVEL_RECLINE_MS  %uu\n",
           (unsigned)MOTION_TRAVEL_RECLINE_MS);
    printf("#define SOCOZI_TRAVEL_HEADREST_MS %uu\n",
           (unsigned)MOTION_TRAVEL_HEADREST_MS);
    printf("#define SOCOZI_HOME_MS %uu\n", (unsigned)MOTION_HOME_MS);
#endif

    return 0;
}
